apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-worker
  labels:
    app: productservice-worker
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice-worker
  template:
    metadata:
      labels:
        app: productservice-worker
        component: worker
    spec:
      containers:
        - name: workflow-worker
          image: productservice:latest
          imagePullPolicy: Never
          command: ["/app/productservice", "workflow-worker"]
          env:
            - name: PRODUCT_HTTP_ADDRESS
              value: ":8084"
            - name: PRODUCT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PRODUCT_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: productservice-db-secret
                  key: DB_NAME
            - name: PRODUCT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: productservice-db-secret
                  key: DB_USER
            - name: PRODUCT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: productservice-db-secret
                  key: DB_PASSWORD
            - name: PRODUCT_TEMPORAL_HOST
              value: temporal.infrastructure.svc.cluster.local:7233