services:
  userservice:
    build:
      context: ./rp-userservice-main
    container_name: userservice
    command:
      - service
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      USER_DATABASE_HOST: userservice-db
      USER_DATABASE_NAME: userservice_db
      USER_DATABASE_USER: userservice
      USER_DATABASE_PASSWORD: 12345Q
    depends_on:
      userservice-db:
        condition: service_healthy

  userservice-message-handler:
    build:
      context: ./rp-userservice-main
    container_name: userservice-message-handler
    command:
      - message-handler
    environment:
      USER_DATABASE_HOST: userservice-db
      USER_DATABASE_NAME: userservice_db
      USER_DATABASE_USER: userservice
      USER_DATABASE_PASSWORD: 12345Q
      USER_AMQP_HOST: rabbitmq
      USER_AMQP_USER: guest
      USER_AMQP_PASSWORD: guest
    depends_on:
      userservice-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  productservice:
    build:
      context: ./rp-productservice
    container_name: productservice
    command:
      - service
    ports:
      - "8083:8081"
      - "8084:8082"
    environment:
      PRODUCT_DATABASE_HOST: productservice-db
      PRODUCT_DATABASE_NAME: productservice_db
      PRODUCT_DATABASE_USER: productservice
      PRODUCT_DATABASE_PASSWORD: 12345Q
    depends_on:
      productservice-db:
        condition: service_healthy

  productservice-message-handler:
    build:
      context: ./rp-productservice
    container_name: productservice-message-handler
    command:
      - message-handler
    environment:
      PRODUCT_DATABASE_HOST: productservice-db
      PRODUCT_DATABASE_NAME: productservice_db
      PRODUCT_DATABASE_USER: productservice
      PRODUCT_DATABASE_PASSWORD: 12345Q
      PRODUCT_AMQP_HOST: rabbitmq
      PRODUCT_AMQP_USER: guest
      PRODUCT_AMQP_PASSWORD: guest
    depends_on:
      productservice-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  paymentservice:
    build:
      context: ./rp-paymentservice
    container_name: paymentservice
    command:
      - service
    ports:
      - "8085:8081"
      - "8086:8082"
    environment:
      PAYMENT_DATABASE_HOST: paymentservice-db
      PAYMENT_DATABASE_NAME: paymentservice_db
      PAYMENT_DATABASE_USER: paymentservice
      PAYMENT_DATABASE_PASSWORD: 12345Q
    depends_on:
      paymentservice-db:
        condition: service_healthy

  paymentservice-message-handler:
    build:
      context: ./rp-paymentservice
    container_name: paymentservice-message-handler
    command:
      - message-handler
    environment:
      PAYMENT_DATABASE_HOST: paymentservice-db
      PAYMENT_DATABASE_NAME: paymentservice_db
      PAYMENT_DATABASE_USER: paymentservice
      PAYMENT_DATABASE_PASSWORD: 12345Q
      PAYMENT_AMQP_HOST: rabbitmq
      PAYMENT_AMQP_USER: guest
      PAYMENT_AMQP_PASSWORD: guest
    depends_on:
      paymentservice-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  orderservice:
    build:
      context: ./rp-orderservice
    container_name: orderservice
    command:
      - service
    ports:
      - "8087:8081"
      - "8088:8082"
    environment:
      ORDER_DATABASE_HOST: orderservice-db
      ORDER_DATABASE_NAME: orderservice_db
      ORDER_DATABASE_USER: orderservice
      ORDER_DATABASE_PASSWORD: 12345Q
    depends_on:
      orderservice-db:
        condition: service_healthy

  orderservice-message-handler:
    build:
      context: ./rp-orderservice
    container_name: orderservice-message-handler
    command:
      - message-handler
    environment:
      ORDER_DATABASE_HOST: orderservice-db
      ORDER_DATABASE_NAME: orderservice_db
      ORDER_DATABASE_USER: orderservice
      ORDER_DATABASE_PASSWORD: 12345Q
      ORDER_AMQP_HOST: rabbitmq
      ORDER_AMQP_USER: guest
      ORDER_AMQP_PASSWORD: guest
    depends_on:
      orderservice-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notificationservice:
    build:
      context: ./rp-notificationservice
    container_name: notificationservice
    command:
      - service
    ports:
      - "8089:8081"
      - "8090:8082"
    environment:
      NOTIFICATION_DATABASE_HOST: notificationservice-db
      NOTIFICATION_DATABASE_NAME: notificationservice_db
      NOTIFICATION_DATABASE_USER: notificationservice
      NOTIFICATION_DATABASE_PASSWORD: 12345Q
    depends_on:
      notificationservice-db:
        condition: service_healthy

  notificationservice-message-handler:
    build:
      context: ./rp-notificationservice
    container_name: notificationservice-message-handler
    command:
      - message-handler
    environment:
      NOTIFICATION_DATABASE_HOST: notificationservice-db
      NOTIFICATION_DATABASE_NAME: notificationservice_db
      NOTIFICATION_DATABASE_USER: notificationservice
      NOTIFICATION_DATABASE_PASSWORD: 12345Q
      NOTIFICATION_AMQP_HOST: rabbitmq
      NOTIFICATION_AMQP_USER: guest
      NOTIFICATION_AMQP_PASSWORD: guest
    depends_on:
      notificationservice-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  userservice-db:
    image: "mysql:8.3"
    container_name: userservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "userservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: userservice_db
      MYSQL_USER: userservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  productservice-db:
    image: "mysql:8.3"
    container_name: productservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "productservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: productservice_db
      MYSQL_USER: productservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3307:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  paymentservice-db:
    image: "mysql:8.3"
    container_name: paymentservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "paymentservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: paymentservice_db
      MYSQL_USER: paymentservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3308:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  orderservice-db:
    image: "mysql:8.3"
    container_name: orderservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "orderservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: orderservice_db
      MYSQL_USER: orderservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3309:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  notificationservice-db:
    image: "mysql:8.3"
    container_name: notificationservice-db
    command: [ "--max_connections=100" ]
    volumes:
      - "notificationservice-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: notificationservice_db
      MYSQL_USER: notificationservice
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3310:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq/mnesia"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  userservice-db-data:
  productservice-db-data:
  paymentservice-db-data:
  orderservice-db-data:
  notificationservice-db-data:
  rabbitmq-data: