apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-worker
  labels:
    app: orderservice-worker
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice-worker
  template:
    metadata:
      labels:
        app: orderservice-worker
        component: worker
    spec:
      containers:
        - name: workflow-worker
          image: orderservice:latest
          imagePullPolicy: Never
          command: ["/app/orderservice", "workflow-worker"]
          env:
            - name: ORDER_HTTP_ADDRESS
              value: ":8084"
            - name: ORDER_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: ORDER_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: orderservice-db-secret
                  key: DB_NAME
            - name: ORDER_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: orderservice-db-secret
                  key: DB_USER
            - name: ORDER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderservice-db-secret
                  key: DB_PASSWORD
            - name: ORDER_TEMPORAL_HOST
              value: temporal.infrastructure.svc.cluster.local:7233